---

snakeoil_extract_to: /etc/snakeoil

snakeoil_domain: molecule.lan

snakeoil_life_time: 20

snakeoil_dhparam: 2048

snakeoil_alt_names:
  - dns:
      - molecule.lan
      - chartmuseum.molecule.lan

...
