---

- name: flush handlers
  ansible.builtin.meta: flush_handlers

- name: ensure chartmuseum is enabled on boot
  become: true
  when:
    - not running_in_check_mode
  ansible.builtin.service:
    name: chartmuseum
    enabled: true
    state: started

...
